name: watertracker
description: "A new Flutter watertracker app."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter 
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8  
  flutter_lints: ^4.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
